spring:
  application:
    name: sc-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
logging:
  level:
    issac.study.scdemo.scweb: debug

feign:
  okhttp:
    enabled: true

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
