eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
